project:
  type: website

website:
  title: "Regen_Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 1_Copied_Code.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



